# Generated by Django 4.0.5 on 2022-06-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_transaction_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='token',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
