# Generated by Django 4.0.4 on 2022-08-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_alter_transaction_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='mount',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.CharField(choices=[('+', 'add'), ('-', 'cost')], default='+', max_length=1),
        ),
    ]
