# Generated by Django 4.0.3 on 2022-03-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fund',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
