# Generated by Django 4.0.3 on 2022-03-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fund',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
